# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: "My cool website"

# Your name to show in the footer
author: "John Doe"

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Work Experience: "workexperience"
  Education: "education"
  Skills: "skills"
  Projects: "projects"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar

avatar: "/assets/img/avatar.jpg"


# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "jdoe@gmail.com"
  github: j99doe
  linkedin: jdoe99

extra-links:
    - url: "somecoolname"
      description: twitter
    - url: "MyLongBitBucketUsername"
      description: bitbucket
    

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: This website is a virtual proof that I'm awesome

# --- General options --- #


# --- Colours / background image --- #



navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"


# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/


kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

collections:
  projects:
    output: true
    permalink: /:collection/:path/
  workexperience:
    output: true
    permalink: /:collection/:path/

defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false

defaults:
  # _workexperience
  - scope:
      path: ""
      type: workexperience
    values:
      layout: single
      author_profile: true
      share: false


include:
  - _pages

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap

